config/routes.rb
FallGambit::Application.routes.draw do

  devise_for :users
  put "games/:id/move", to: "games#move"
  resources :games, :only => [:new, :create, :show, :update]
  resources :pieces, :only => [:show, :update]
  resources :users, :only => :show

  resources :games do
    member do
      put :forfeit, to: "games#forfeit"
      put :request_draw, to: "games#request_draw"
      put :accept_draw, to: "games#accept_draw"
      put :reject_draw, to: "games#reject_draw"
    end
  end

  resources :pieces do
    member do
      get 'promotion_choice', :action => :promotion_choice
      put 'promotion_choice', :action => :promotion_choice
      patch 'promote_pawn', :action => :promote_pawn
    end
  end

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @games = Game.all
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_available_games.html.erb
<h3 class="text-center">Games players can join:</h3>
<% @games.each do |game|  %>
  <div class="list-group">
    <% if game.player_missing? %>
      <div class="list-group-item">
        <h4><%= game.game_name %></h4>
        <p>Last Update: <%= game.updated_at.strftime("%B %d, %Y") %></p>
        <% if current_user && current_user.id == game.white_user_id %>
          <%= link_to 'Waiting For Black To Join', game_path(game, id: game.id), :class => 'btn btn-default btn-large join-game-link' %>
        <% elsif current_user && current_user.id == game.black_user_id %>
          <%= link_to 'Waiting For White To Join', game_path(game, id: game.id), :class => 'btn btn-default btn-large join-game-link' %>
        <% else %>
          <%= link_to 'Join Game', game_path(game, id: game.id), method: :patch, :class => 'btn btn-success btn-large join-game-link' %>
          <%= link_to 'Watch Game', game_path(game, id: game.id), :class => 'btn btn-info btn-large join-game-link' %>
        <% end %>
      </div>
    <% end  %>
  </div>
<% end %>
<br />
<h3 class="text-center">Games in Progress:</h3>
<% @games.each do |game| %>
  <div class="list-group">
    <% if !game.player_missing? && game.game_winner.nil? && game.draw == false%>
      <div class="list-group-item">
        <h4><%= game.game_name %></h4>
        <p>Last Update: <%= game.updated_at.strftime("%B %d, %Y") %></p>
        <% if current_user && (current_user.id == game.white_user_id || current_user.id == game.black_user_id) %>
          <% if game.user_turn == current_user.id %>
            <%= link_to 'Your Turn!', game_path(game, id: game.id), :class => 'btn btn-warning btn-large join-game-link' %>
          <% else %>
            <%= link_to "Your Opponent's Turn", game_path(game, id: game.id), :class => 'btn btn-primary btn-large join-game-link' %>
          <% end %>
        <% else %>
          <%= link_to 'Watch Game', game_path(game, id: game.id), :class => 'btn btn-success btn-large join-game-link' %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>
<br />
<h3 class="text-center">Completed Games:</h3>
<% @games.each do |game| %>
  <div class="list-group">
    <% if !game.game_winner.nil? || game.draw == true %>
      <div class="list-group-item">
        <h4><%= game.game_name %></h4>
        <p>Last Update: <%= game.updated_at.strftime("%B %d, %Y") %></p>
        <% if game.draw == true %>
          <%= link_to 'Draw!', game_path(game, id: game.id), :class => 'btn btn-info btn-large join-game-link' %>
        <% elsif current_user && game.game_winner == current_user.id %>
          <%= link_to 'You won!', game_path(game, id: game.id), :class => 'btn btn-info btn-large join-game-link' %>
        <% elsif current_user && (current_user.id == game.white_user.id || current_user.id == game.black_user_id) %>
          <%= link_to 'You lost!', game_path(game, id: game.id), :class => 'btn btn-danger btn-large join-game-link' %>
        <% elsif game.game_winner == game.white_user_id %>
          <%= link_to 'White wins!', game_path(game, id: game.id), :class => 'btn btn-info btn-large join-game-link' %>
        <% elsif game.game_winner == game.black_user_id %>
          <%= link_to 'Black wins!', game_path(game, id: game.id), :class => 'btn btn-info btn-large join-game-link' %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>
<%= subscribe_to "/game_list_updates" %>

app/views/welcome/index.html.erb
<br />
<br />
<div class="row">
<div class="col-md-6 col-md-offset-3 text-center">
    <h2>Welcome to the Fall Gambit Chess App!</h2>
    <br />
    <%= link_to 'Start A New Game', new_game_path, class: 'btn btn-success btn-large' %>
    <br />
    <br />
    <% if @games.present? %>
      <%= render partial: 'available_games' %>
    <% end %>
  </div>
</div>