config/routes.rb
FallGambit::Application.routes.draw do

  devise_for :users
  put "games/:id/move", to: "games#move"
  resources :games, :only => [:new, :create, :show, :update]
  resources :pieces, :only => [:show, :update]
  resources :users, :only => :show

  resources :games do
    member do
      put :forfeit, to: "games#forfeit"
      put :request_draw, to: "games#request_draw"
      put :accept_draw, to: "games#accept_draw"
      put :reject_draw, to: "games#reject_draw"
    end
  end

  resources :pieces do
    member do
      get 'promotion_choice', :action => :promotion_choice
      put 'promotion_choice', :action => :promotion_choice
      patch 'promote_pawn', :action => :promote_pawn
    end
  end

  root 'welcome#index'

end

app/models/piece.rb
class Piece < ActiveRecord::Base
  belongs_to :user
  belongs_to :game
  attr_accessor :flash_message
  validates :x_position, :presence => true,
                         :numericality => { greater_than_or_equal_to: 0,
                                            less_than_or_equal_to: 7 },
                         allow_nil: true
  validates :y_position, :presence => true,
                         :numericality => { greater_than_or_equal_to: 0,
                                            less_than_or_equal_to: 7 },
                         allow_nil: true
  after_initialize :set_image

  # Lines 16-22 all part of STI: to break it disable line 6 or give
  # self.inheritance_column a fake field name ~AMP
  self.inheritance_column = :piece_type
  scope :pawns, -> { where(piece_type: "Pawn") }
  scope :queens, -> { where(piece_type: "Queen") }
  scope :kings, -> { where(piece_type: "King") }
  scope :rooks, -> { where(piece_type: "Rook") }
  scope :knights, -> { where(piece_type: "Knight") }
  scope :bishops, -> { where(piece_type: "Bishop") }

  def self.piece_types
    %w(Pawn Queen King Rook Knight Bishop)
  end

  def x_y_coords
    x_y_coordinates = []
    x_y_coordinates << x_position
    x_y_coordinates << y_position
    x_y_coordinates
  end

  def set_image
    color ? color_string = "white" : color_string = "black"
    self.image_name = "#{color_string}-#{piece_type.downcase}.png"
  end

  def move_to!(x, y)
    orig_x = self.x_position
    orig_y = self.y_position
    @target = game.pieces.where(:x_position => x, :y_position => y).take
    return self.castle!(@target) if self.piece_type == "King" && self.can_castle?(@target)
    unless valid_move?(x, y)
      self.flash_message = "Invalid move!"
      return false
    end
    if game.puts_king_in_check?(self, x, y) 
      self.flash_message = "Can't put or leave yourself in check!"
      return false 
    end
    if self.piece_type == "Pawn" && self.en_passant?(x, y)
      capture(self.en_passant?(x, y), x, y) #en_passant? returns captured piece
    elsif @target.nil?
      update_attributes(:x_position => x, :y_position => y, :has_moved => true)
    else
      if color == @target.color
        self.flash_message =  "Invalid move: same color piece"
        return false
      end
      capture(@target, x, y)
    end
    game.update_attributes(last_moved_piece_id: self.id, last_moved_prev_x_pos: orig_x, last_moved_prev_y_pos: orig_y)
    return true
  end

  def capture(target, x, y)
    # target is the piece to capture. x and y are capturing piece destination
    update_attributes(:x_position => x, :y_position => y, :has_moved => true)
    target.update_attributes(:captured => true, :x_position => nil,
                              :y_position => nil)
  end

  def find_piece(x, y)
    game.pieces.where("x_position = ? AND y_position = ?", x, y)
  end

  def square_occupied?(x, y)
    find_piece(x, y).any?
  end

  def range_occupied?(x1, x2, y1, y2)
    # Use Restriction: x1 < x2, y1 < y2
    game.pieces
      .where("x_position BETWEEN ? AND ? AND y_position BETWEEN ? AND ?",
             x1, x2, y1, y2).any?
  end

  def is_obstructed?(dest_x, dest_y)
    state_x = x_position
    state_y = y_position
    delta_x = dest_x - state_x
    delta_y = dest_y - state_y

    if delta_x != 0 && delta_y != 0 && delta_x.abs != delta_y.abs
      # this handles invalid input or invalid moves.
      # should this include tests for values over 7 and non-numeric input?
      self.flash_message = "Invalid input or invalid move."
      return true
    elsif delta_y == 0 && delta_x > 0 && delta_x.abs > 1
      # horizontal move where start is < destination and distance > 1
      return self.range_occupied?((state_x + 1), (dest_x - 1), state_y, state_y)
    elsif delta_y == 0 && delta_x < 0 && delta_x.abs > 1
      # horizontal move where start is > destination and distance > 1
      return self.range_occupied?((dest_x + 1), (state_x - 1), state_y, state_y)
    elsif delta_y == 0 && delta_x.abs <= 1
      # horizontal move to next square or delta 0
      return false
    elsif delta_x == 0 && delta_y > 0 && delta_y.abs > 1
      # vertical move where start is < destination and distance > 1
      return self.range_occupied?(state_x, state_x, (state_y + 1), (dest_y - 1))
    elsif delta_x == 0 && delta_y < 0 && delta_y.abs > 1
      # vertical move where start is > destination and distance > 1
      return self.range_occupied?(state_x, state_x, (dest_y + 1), (state_y - 1))
    elsif delta_x == 0 && delta_y.abs <= 1
      # vertical move to next square or delta 0
      return false
    elsif delta_x == delta_y && delta_x > 0
      # NE move: positive X, positive Y diagonal
      steps = delta_x - 1
      steps.times do
        state_x += 1
        state_y += 1
        return true if self.square_occupied?((state_x), (state_y))
      end
      return false
    elsif delta_x == delta_y && delta_x < 0
      # SW move: negative X negative Y diagonal
      steps = delta_x.abs - 1
      steps.times do
        state_x -= 1
        state_y -= 1
        return true if self.square_occupied?((state_x), (state_y))
      end
      return false
    elsif delta_x > 0 && delta_y < 0 && delta_x == delta_y.abs
      # SE move: positive X, negative Y diagonal
      steps = delta_x - 1
      steps.times do
        state_x += 1
        state_y -= 1
        return true if self.square_occupied?((state_x), (state_y))
      end
      return false
    elsif delta_x < 0 && delta_y > 0 && delta_x.abs == delta_y
      # NW move: negative X, positive Y diagonal
      steps = delta_y - 1
      steps.times do
        state_x -= 1
        state_y += 1
        return true if self.square_occupied?((state_x), (state_y))
      end
      return false
    end
  end
end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  before_action :authenticate_user!
  before_action :game_must_not_be_over, :must_be_users_turn, :must_be_users_piece
  after_action :flash_notice, only: :update

  def show
    @piece = Piece.find(params[:id])
    @current_game = current_game
    if @piece.game.player_missing?
      flash[:alert] = "Cannot move until both players have joined!"
      redirect_to game_path(@piece.game) and return
    end
  end

  def update
    if @piece.game.player_missing?
      flash[:alert] = "Cannot move until both players have joined!"
      redirect_to game_path(@piece.game) and return
    end
    @piece = Piece.find(params[:id])
    new_x = params[:x].to_i
    new_y = params[:y].to_i
    if @piece.piece_type == "Pawn" && @piece.promote_at?(new_x, new_y) # pawn can be promoted
      # set global variables for new view and form submission- kind of ugly, but it works
      # need to do this in case the user does not submit the promotion form, need to revert piece(s) to 
      # previous state(s)
      $old_x = @piece.x_position
      $old_y = @piece.y_position
      $intended_x = new_x
      $intended_y = new_y
      respond_to do |format|
        format.json { redirect_to promotion_choice_piece_path(@piece) }
        format.html { redirect_to promotion_choice_piece_path(@piece) }
      end
      return
    end
    if @piece.move_to!(new_x, new_y)
      opponent_king = @piece.game.kings.where.not(color: @piece.color).first
      if @piece.game.checkmate?(opponent_king) # current player placed other player in checkmate - wins!
        @piece.game.update_attributes(game_winner: @piece.user_id) # set game winner
        # update user stats
        if User.find(@piece.user_id) == black_user
          black_user.update_attributes(user_wins: black_user.user_wins + 1)
          white_user.update_attributes(user_losses: white_user.user_losses + 1)
        else
          white_user.update_attributes(user_wins: white_user.user_wins + 1)
         black_user.update_attributes(user_losses: black_user.user_losses + 1)
        end
        flash[:notice] = "Checkmate! You win!" # will only get set and display on winner's turn
        update_game_listing # refresh game listing in real-time
      else
        # check for stalemate of other player after move and set game model field
        if @piece.game.stalemate!(opponent_king)
          @piece.game.user_turn == @piece.game.white_user_id ? other_player = "Black" : other_player = "White"
          # update user stats
          white_user.update_attributes(user_draws: white_user.user_draws + 1)
          black_user.update_attributes(user_draws: black_user.user_draws + 1)
          flash[:notice] = other_player + " is in stalemate! Game is a draw."
          update_game_listing # refresh game listing in real-time
        else
          @piece.game.determine_check(opponent_king) # set check field in game model
        end
      end
      # end turn
      @piece.game.finish_turn(@piece.user) # otherwise turn goes to other player
    else
      respond_to do |format|
        format.json { render json: { errors: @piece.errors.full_messages }, :status => 400 }
        format.html { redirect_to game_path(@piece.game) }
      end
      return
    end
    respond_to do |format|
      format.json { render :json => @piece.to_json }
      format.html { redirect_to game_path(@piece.game) }
    end
    begin
      PrivatePub.publish_to("/games/#{@piece.game.id}", "window.location.reload();")
      PrivatePub.publish_to( "/game_list_updates", "window.location.reload();")
    rescue Errno::ECONNREFUSED
      # flash.now[:alert] = "Pushing to Faye Failed"
      return
    end
  end

  def promotion_choice
    # can/should eventually move this logic into a model
    # make sure choices don't place opponent into stalemate, pass choices to radio buttons in form
    @piece = Piece.find(params[:id])
    dest_piece = @piece.game.pieces.where(x_position: $intended_x, y_position: $intended_y).first
    if !dest_piece.nil? 
      dest_piece.update_attributes(x_position: nil, y_position: nil, captured: true) # temp capture to check for stalemate
    end
    @piece.update_attributes(x_position: $intended_x, y_position: $intended_y) # temp move to check for stalemate
    # need to loop through Queen and Knight to check for stalemate on promotion
    @promotion_check_for_stalemate = %w(Queen Knight)
    @button_list = [] # will show up as radio buttons passed to the user input form
    @promotion_check_for_stalemate.each do |promo|
      @piece.promote!(promo) # try promoting piece to Queen/Knight
      @piece = Piece.find(params[:id]) #reload new type
      if !@piece.game.stalemate?(@piece.game.kings.where.not(color: @piece.color).first) # doesn't put game into stalemate
        @button_list << [promo, promo] # add piece to possible promotion type if it doesn't cause a stalemate
      end
      # reset piece to Pawn so promote! can be called again since it's a pawn method
      @piece.update(piece_type: "Pawn")
      @piece.save!
      @piece = Piece.find(params[:id]) # reload original pawn instance type
    end
    # can always pick rook and bishop
    @button_list << ['Rook', 'Rook'] << ['Bishop', 'Bishop']
    # full list passed to user input form (if no stalemates) should be:
    #@button_list = [['Queen', 'Queen'],['Knight', 'Knight'],['Rook', 'Rook'],['Bishop', 'Bishop']]
    # reset pawn/captured piece to previous positions in case promotion cancelled without submitting form
    if !dest_piece.nil? 
      dest_piece.update_attributes(x_position: $intended_x, y_position: $intended_y, captured: false) # reset
    end
    @piece.update_attributes(x_position: $old_x, y_position: $old_y) # reset
  end

  def promote_pawn
    # perform the actual promotion and moving of the piece on form submission
    if @piece.move_to!($intended_x, $intended_y) #try to move piece
      type_update = pawn_update_params[:piece_type] # grab from input form params
      if @piece.promote!(type_update) # was promotion succesful?
        @piece = Piece.find(params[:id]) #reload as new piece type
        # check for checkmate, stalemate, or determine check and advance turn
        # a lot of this is pulled from move_to!, but we have to check again with the new piece type
        opponent_king = @piece.game.kings.where.not(color: @piece.color).first
        if @piece.game.checkmate?(opponent_king) # current player placed other player in checkmate - wins!
          @piece.game.update_attributes(game_winner: @piece.user_id) # set game winner
          flash[:notice] = "Checkmate! You win!" # will only get set and display on winner's turn
        elsif @piece.game.stalemate!(opponent_king) #ideally we can make sure this never happens by limiting promotion choices
          @piece.game.user_turn == @piece.game.white_user_id ? other_player = "Black" : other_player = "White"
          flash[:notice] = other_player + " is in stalemate! Game is a draw."
        else
        @piece.game.determine_check(opponent_king) # set check field in game model
        @piece.game.finish_turn(@piece.user) # next player's turn
        flash[:notice] = "Pawn promoted!"
        end
      else
        # promote failed so move pawn back, don't advance turn
        @piece.update_attributes(x_position: $old_x, y_position: $old_y)
        flash[:alert] = "Could not promote pawn!"
      end
    end
    redirect_to game_path(@piece.game)
    begin
      PrivatePub.publish_to("/games/#{@piece.game.id}", "window.location.reload();")
    rescue Errno::ECONNREFUSED
      # flash.now[:alert] = "Pushing to Faye Failed"
      return
    end
  end

  private

  helper_method :current_game, :show_piece_td

  def flash_notice
    if @piece.flash_message.present?
      flash[:alert] = @piece.flash_message
    end
  end

  def black_user
    black_user ||= User.find(@piece.game.black_user.id)
  end

  def white_user
    white_user ||= User.find(@piece.game.white_user.id)
  end

  def current_game
    @piece = Piece.find(params[:id])
    @current_game ||= @piece.game
  end

  def board_display_piece_query(row, column)
    current_game.pieces.find do |f|
      f["x_position"] == column && f["y_position"] == row
    end
  end

  def show_piece_td(row, column)
    @current_game = current_game
    find_piece = board_display_piece_query(row, column)
    board_square = "<td data-x-position='#{column}'"
    url = piece_path(Piece.find(params[:id]))
    url += "?x=#{column}&y=#{row}"
    if find_piece.nil?
      board_square += ">"
      board_square += ActionController::Base.helpers.link_to '',
                                                             url, method: :put
    else
      board_square += " data-piece-id='#{piece_id(find_piece)}' "
      board_square += "data-piece-type='#{piece_type(find_piece)}'>"
      image = ActionController::Base.helpers.image_tag find_piece
              .image_name, size: '40x45',
                           class: 'img-responsive center-block'
      board_square += ActionController::Base.helpers.link_to image,
                                                             url, method: :put
    end
    board_square + "</td>"
  end

  def piece_id(piece)
    piece.present? ? piece.id : nil
  end

  def piece_type(piece)
    piece.present? ? piece.piece_type : nil
  end

  def game_must_not_be_over
    # run before any pieces controller action
    if !current_game.game_winner.nil?
      current_game.game_winner == current_game.black_user_id ? winner = "black" : winner = "white"
      flash[:alert] = "Game is over, " + winner + " wins!"
      redirect_to game_path(current_game) and return
    elsif current_game.draw?
      current_game.user_turn == current_game.white_user_id ? current_turn = "White" : current_turn = "Black"
      flash[:notice] = "Game is a draw! " + current_turn + " can't move without going into check!"
      redirect_to game_path(current_game) and return
    end 
  end

app/views/pieces/_blackside.html.erb
<!-- _blackside.html.erb 20160108 ~AMP -->
<div class="col-xs-12 col-sm-3 text-center blackside">
  <h4>Black Piece Controls</h4>
  <% if !current_game.black_user.nil? %>
    <p><%= current_game.black_user.email %></p>
  <% else %>
    <p>Waiting for player</p>
  <% end %>
  <% if current_game.user_turn == current_game.black_user_id %>
    <% if @piece.piece_type == "King" %>
      <% if @piece.can_castle?(current_user.rooks.where(x_position: 0).take) %>
        <b>Click on Queen's Rook to Castle Queenside</b>
      <% end %>
      <% if @piece.can_castle?(current_user.rooks.where(x_position: 7).take) %>
        <b>Click on King's Rook to Castle Kingside</b>
      <% end %>
    <% end %>
  <% end %>
  <p>Captured Pieces:</p>
  <% current_game.pieces.where(color: true, captured: true).order(:updated_at).each do |capped_piece| %>
    <%= image_tag capped_piece.image_name, size: "25x25" %> 
  <% end %>
</div>

app/views/pieces/_whiteside.html.erb
<!-- _whiteside.html.erb 20160108 ~AMP -->
<div class="col-xs-12 col-sm-3 text-center whiteside">
  <h4>White Piece Controls</h4>
  <% if !current_game.white_user.nil? %>
    <p><%= current_game.white_user.email %></p>
  <% else %>
    <p>Waiting for player</p>
  <% end %>
  <% if current_game.user_turn == current_game.white_user_id %>
    <% if @piece.piece_type == "King" %>
      <% if @piece.can_castle?(current_user.rooks.where(x_position: 0).take) %>
        <b>Click on Queen's Rook to Castle Queenside</b>
      <% end %>
      <% if @piece.can_castle?(current_user.rooks.where(x_position: 7).take) %>
        <b>Click on King's Rook to Castle Kingside</b>
      <% end %>
    <% end %>
  <% end %>
  <p>Captured Pieces:</p>
  <% current_game.pieces.where(color: false, captured: true).order(:updated_at).each do |capped_piece| %>
    <%= image_tag capped_piece.image_name, size: "25x25" %>
  <% end %>
</div>

app/views/pieces/promotion_choice.html.erb
<br />
<br />
<div class="row">
  <h3 class ="text-center">Promote Your Pawn</h3>
  <div class="col-md-2 col-md-offset-5">
    <%= simple_form_for @piece, :url => promote_pawn_piece_path, method: :patch do |f| %>
      <%= f.input :piece_type, collection: @button_list, as: :radio_buttons, label: 'Promote to:', class: 'form-control', :checked => @button_list[0] %>
      <br />
      <%= f.submit "Promote!", :class => 'btn btn-primary' %> 
      <br />
      <br />
      <%= link_to "Cancel", game_path(@piece.game), {:class=>"btn btn-danger"} %>
      <br />
    <% end %>
    <br />
  </div>
</div>

app/views/pieces/show.html.erb
<!-- pieces.show page  -->
<% if current_game %>
  <br />
  <br />
  <div class="row">
    <div class="col-md-6 col-md-offset-3 text-center">
      <h3><%= current_game.game_name %></h3>
      <br />
        <% if !current_game.game_winner.nil? %>
          <% if current_game.game_winner == current_game.white_user_id %>
            <% if current_game.forfeit? %>
              <h4 class="turn-indicator">Black player forfeit. White player wins!</h4>
            <% else %>
              <h4 class="turn-indicator">Checkmate! White player wins!</h4>
            <% end %>
          <% else %>
            <% if current_game.forfeit? %>
              <h4 class="turn-indicator">White player forfeit. Black player wins!</h4>
            <% else %>
              <h4 class="turn-indicator">Checkmate! Black player wins!</h4>
            <% end %>
          <% end %>
        <% elsif current_game.draw? %>
          <% if current_game.user_turn == current_game.white_user_id %>
            <% if !current_game.draw_request.nil? %>
              <h4 class="turn-indicator">Game is a draw! Draw offer accepted. </h4>
            <% else %>
              <h4 class="turn-indicator">Game is a draw! White player in stalemate!</h4>
            <% end %>
          <% else %>
            <% if !current_game.draw_request.nil? %>
              <h4 class="turn-indicator">Game is a draw! Draw offer accepted. </h4>
            <% else %>
              <h4 class="turn-indicator">Game is a draw! Black player in stalemate!</h4>
            <% end %>
          <% end %>
        <% elsif current_game.player_missing? %>
          <% if current_game.white_user_id.nil? %>
            <h4 class="turn-indicator">Waiting for white player to join...</h4>
          <% else %>
            <h4 class="turn-indicator">Waiting for black player to join...</h4>
          <% end %>
        <% elsif current_user && current_game.user_turn == current_user.id %>
          <% if current_game.user_turn == current_game.white_user_id %>
            <h4 class="turn-indicator">It is your turn! (white)</h4>
          <% else %>
            <h4 class="turn-indicator">It is your turn! (black)</h4>
          <% end %>
        <% else  %>
          <% if current_user %>
            <% if current_game.user_turn == current_game.white_user_id %>
              <h4 class="turn-indicator">It is your opponent's turn (white)</h4>
            <% else %>
              <h4 class="turn-indicator">It is your opponent's turn (black)</h4>
            <% end %>
          <% else %>
            <% if current_game.user_turn == current_game.white_user_id %>
              <h4 class="turn-indicator">White player's turn</h4>
            <% else %>
              <h4 class="turn-indicator">Black player's turn</h4>
            <% end %>
          <% end %>
        <% end %>
      <br />
      <% if current_game.check? && current_game.game_winner.nil?%>
        <% if current_game.user_turn == current_game.white_user_id %>
          <h4 class ="check-message">White player is in check!</h4>
        <% else %>
          <h4 class ="check-message">Black player is in check!</h4>
        <% end %>
      <% end %>
    </div>
  </div>
  <!-- Arrangement of partials and chessboards is optimized for mobile. -->
  <% if current_user && current_user.id == current_game.black_user_id %>
    <%= render partial: 'whiteside' %>
    <div class="col-xs-12 col-sm-6">
      <table class="chessboard">
        <% (0..7).each do |row| %>
            <tr data-y-position="<%= row %>" >
              <% (0..7).to_a.reverse.each do |column| %>
                <%= show_piece_td(row, column).html_safe %>
              <% end %>
            </tr>
        <% end %>
      </table>
    </div>
    <%= render partial: 'blackside' %>
  <% else %>
    <%= render partial: 'blackside' %>
    <div class="col-xs-12 col-sm-6">
      <table class="chessboard">
        <% (0..7).to_a.reverse.each do |row| %>
          <tr data-y-position="<%= row %>" >
            <% (0..7).each do |column| %>
              <%= show_piece_td(row, column).html_safe %>
            <% end %>
          </tr>
        <% end %>
      </table>
    </div>
    <%= render partial: 'whiteside' %>
  <% end %>
<% end %>