config/routes.rb
FallGambit::Application.routes.draw do

  devise_for :users
  put "games/:id/move", to: "games#move"
  resources :games, :only => [:new, :create, :show, :update]
  resources :pieces, :only => [:show, :update]
  resources :users, :only => :show

  resources :games do
    member do
      put :forfeit, to: "games#forfeit"
      put :request_draw, to: "games#request_draw"
      put :accept_draw, to: "games#accept_draw"
      put :reject_draw, to: "games#reject_draw"
    end
  end

  resources :pieces do
    member do
      get 'promotion_choice', :action => :promotion_choice
      put 'promotion_choice', :action => :promotion_choice
      patch 'promote_pawn', :action => :promote_pawn
    end
  end

  root 'welcome#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessor :creator_plays_as_black # for checkbox access
  has_many :pieces
  has_one  :last_moved_piece, class_name: 'Piece', foreign_key: :last_moved_piece_id
  belongs_to :white_user, class_name: 'User', foreign_key: :white_user_id
  belongs_to :black_user, class_name: 'User', foreign_key: :black_user_id
  validates :game_name, presence: { :message => "Game name is required!" }
  validates :white_user_id,
            presence: true, unless: :black_user_id?, on: :create
  validates :black_user_id,
            presence: true, unless: :white_user_id?, on: :create
  validate :user_id_exists, on: :create
  validate :white_user_id_exists, if: :white_user_id?, on: :update
  validate :black_user_id_exists, if: :black_user_id?, on: :update
  validate :users_must_be_different, on: :update
  validate :user_turn_must_be_valid, on: :update
  after_create :populate_board!

  # This is part of STI ~AMP:
  delegate :pawns, :queens, :kings, :knights, :rooks, :bishops, to: :pieces

  def populate_board!
    # Creates all 32 chess pieces with their initial X/Y coordinates.

    # Board is numbered as per standard. X = column, Y = row
    # Bottom (white) rows are 0 and 1, top (black) rows are 6 and 7
    # Make sure to keep this in mind when working the logic, it's set up
    # as the upper right quadrant of a graph (instead of thinking [row, column]
    # coordinates as you normally might for a matrix)
    populate_white_pieces
    populate_black_pieces
    white_user_id.nil? ? set_pieces_black_user_id : set_pieces_white_user_id
  end

  def set_pieces_black_user_id
    pieces.where(color: false).each do |curr_piece|
      curr_piece.update_attributes(user_id: black_user_id)
    end
  end

  def set_pieces_white_user_id
    pieces.where(color: true).each do |curr_piece|
      curr_piece.update_attributes(user_id: white_user_id)
    end
  end

  def set_turn_id (player_id)
    self.user_turn = player_id
    self.save!
  end

  def finish_turn(player)
    if player == black_user
      set_turn_id(white_user_id)
    else
      set_turn_id(black_user_id)
    end
  end

  def current_player
    if self.user_turn == black_user_id
      return self.black_user
    else
      return self.white_user
    end
  end

  def player_missing?
    white_user.nil? || black_user.nil?
  end

  def determine_check(king)
    # if king is in check, returns list of pieces that threaten it - will evaluate to true if present
    # instead of just returning true/false, I have this method return the list of enemy pieces putting the
    # king in check to try to DRY up the code
    threatening_pieces = []
    opponents_pieces = self.pieces.where(color: !king.color, captured: false)
    opponents_pieces.each do |piece|
      if piece.valid_move?(king.x_position, king.y_position)
        self.update_attributes(check_status: 1)
        threatening_pieces << piece
      end
    end
    if threatening_pieces.any?
      return threatening_pieces
    end
    self.update_attributes(check_status: 0)
    return false
  end

  def check?
    check_status == 1 ? true : false
  end

  def puts_king_in_check?(moving_piece, x_dest, y_dest) # move any piece and see if it puts that piece's color king in check
    # have to temporarily move the piece around to see if the king ends up in check
    king = self.pieces.where(color: moving_piece.color, piece_type: "King").first #player's king
    piece_orig_x_pos = moving_piece.x_position
    piece_orig_y_pos = moving_piece.y_position
    if moving_piece.valid_move?(x_dest, y_dest)
      # see if enemy piece is there, temporarily remove it for these checks
      destination_piece = self.pieces.where(color: !king.color, x_position: x_dest, y_position: y_dest).first
      if destination_piece
        destination_piece.update_attributes(x_position: nil, y_position: nil, captured: true)
      end
      moving_piece.update_attributes(x_position: x_dest, y_position: y_dest)
      king.reload # this is in case moving_piece is the king, updates king variable to match
    else
      return nil #nil for bad moves
    end
    opponents_pieces = self.pieces.where(color: !king.color, captured: false)
    opponents_pieces.each do |piece| # see if any piece can capture king
      if piece.valid_move?(king.x_position, king.y_position)
        moving_piece.update_attributes(x_position: piece_orig_x_pos, y_position: piece_orig_y_pos)
        if destination_piece
          destination_piece.update_attributes(x_position: x_dest, y_position: y_dest, captured: false)
        end
        return true
      end
    end
    moving_piece.update_attributes(x_position: piece_orig_x_pos, y_position: piece_orig_y_pos)
    if destination_piece
      destination_piece.update_attributes(x_position: x_dest, y_position: y_dest, captured: false)
    end
    return false
  end

  def stalemate?(king)
    # just checks for stalemate, doesn't set game status
    friendly_pieces = pieces.where(color: king.color, captured: false)
    return false if determine_check(king) # king can't currently be in check
    (0..7).to_a.each do |row| # loop through all board squares
      (0..7).to_a.each do |column| # see if and valid moves which don't put king in check
        friendly_pieces.each do |friendly_piece|
          if friendly_piece.valid_move?(row, column) && !puts_king_in_check?(friendly_piece, row, column)
            return false # found at least one valid move, so not a stalemate
          end
        end
      end
    end
    return true # no valid moves, stalemate!
  end

  def stalemate!(king)
    # sets game database field if game is in stalemate
    return false unless stalemate?(king)
    self.update_attributes(draw: true) # set database field
    return true # no valid moves, stalemate!
  end

  def checkmate?(king)
    # going to assume for now that a valid king object is passed in...
    threatening_pieces = determine_check(king) # piece(s) putting king into check
    return false unless threatening_pieces # king isn't in check!
    # try moving king in every direction to escape check, if any valid move then checkmate is false
    result = puts_king_in_check?(king, king.x_position, king.y_position+1) # up
    if !result && !result.nil? # if false and not nil then it is a valid move out of check
      return false # can escape check
    end
    result = puts_king_in_check?(king, king.x_position+1, king.y_position+1) # up-right
    if !result && !result.nil?
      return false
    end
    result = puts_king_in_check?(king, king.x_position+1, king.y_position) # right
    if !result && !result.nil?
      return false
    end
    result = puts_king_in_check?(king, king.x_position+1, king.y_position-1) # down-right
    if !result && !result.nil?
      return false
    end
    result = puts_king_in_check?(king, king.x_position, king.y_position-1) # down
    if !result && !result.nil?
      return false
    end
    result = puts_king_in_check?(king, king.x_position-1, king.y_position-1) # down-left
    if !result && !result.nil?
      return false
    end
    result = puts_king_in_check?(king, king.x_position-1, king.y_position) # left
    if !result && !result.nil?
      return false
    end
    result = puts_king_in_check?(king, king.x_position-1, king.y_position+1) # up-left
    if !result && !result.nil?
      return false
    end
    result = puts_king_in_check?(king, king.x_position, king.y_position+1) # up
    if !result && !result.nil?
      return false
    end

    threatening_pieces.each do |enemy_piece|
      range_to_check = range_between_pieces(king, enemy_piece) #get x and y coord of squares between king and enemy
      friendly_pieces = self.pieces.where(color: king.color, captured: false).where.not(piece_type: "King") # returns empty array if no results
      friendly_pieces.each do |friendly_piece|
        # can any friendly piece capture threatening piece? then break for this threatening piece
        if friendly_piece.valid_move?(enemy_piece.x_position, enemy_piece.y_position)
          enemy_piece_orig_x_pos = enemy_piece.x_position
          enemy_piece_orig_y_pos = enemy_piece.y_position
          friendly_piece_orig_x_pos = friendly_piece.x_position
          friendly_piece_orig_y_pos = friendly_piece.y_position
          # temporarily move pieces to determine if king still in check
          enemy_piece.update_attributes(x_position: nil, y_position: nil, captured: true)
          friendly_piece.update_attributes(x_position: enemy_piece_orig_x_pos, y_position: enemy_piece_orig_y_pos)
          king_still_checked = determine_check(king)
          # set pieces back to original state
          enemy_piece.update_attributes(x_position: enemy_piece_orig_x_pos, y_position: enemy_piece_orig_y_pos, captured: false)
          friendly_piece.update_attributes(x_position: friendly_piece_orig_x_pos, y_position: friendly_piece_orig_y_pos)
          if !king_still_checked # capturing enemy piece takes king out of check
            return false
          end
        end
        unless enemy_piece.piece_type == "Knight" # can't block knight, and it couldn't be captured by this friendly piece
          # can this friendly piece block check?
          # determine movement path from enemy to king - then see if any friendly piece has valid move within that line
          if !range_to_check.nil? # either an enemy knight or a non-threat (shouldn't happen) - not vert, horiz, or diagonal
            range_to_check.each do |square| # loop through every square between enemy and king (not including their positions)
              if friendly_piece.valid_move?(square[0], square[1]) #pull out x and y values to see if we can block
                friendly_piece_orig_x_pos = friendly_piece.x_position
                friendly_piece_orig_y_pos = friendly_piece.y_position
                # temporarily update friendly piece to blocking position to see if it blocks check

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :move]

  def new
    @game = Game.new
  end

  def create
    @game = Game.create(game_create_params)
    if @game.valid?
      redirect_to game_path(@game)
      begin
        # update game listing in real time
        PrivatePub.publish_to( "/game_list_updates", "window.location.reload();")
      rescue Errno::ECONNREFUSED
        flash.now[:alert] = "Pushing to Faye Failed"
      end
    else
      flash.now[:alert] = "Error creating game!"
      render :new, :status => :unprocessable_entity
    end
  end

  def show
    @game = Game.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render :text => "404 Error - Game Not Found", :status => :not_found
  end

  def update
    @game = Game.find(params[:id])
    if @game.player_missing?
      update_player
      if @game.errors.empty?
        flash[:notice] = "Joined the game!"
        redirect_to game_path(@game)
        begin
          PrivatePub.publish_to("/games/#{@game.id}", "window.location.reload();")
          PrivatePub.publish_to( "/game_list_updates", "window.location.reload();")
        rescue Errno::ECONNREFUSED
          flash.now[:alert] = "Pushing to Faye Failed"
        end
        return
      end
    end
    handle_update_errors 
  end

  def move
    respond_to do |format|
      format.json { redirect_to piece_path(params[:piece_id]) }
      format.html { redirect_to piece_path(params[:piece_id]) }
    end
  end

  def forfeit
    unless current_game.player_missing?
      if current_user.id == current_game.white_user_id
        current_game.update_attributes(game_winner: current_game.black_user_id, forfeit: true)
        black_user.update_attributes(user_wins: black_user.user_wins + 1)
        white_user.update_attributes(user_losses: white_user.user_losses + 1)
      elsif current_user.id == current_game.black_user_id
        current_game.update_attributes(game_winner: current_game.white_user_id, forfeit: true)
        white_user.update_attributes(user_wins: white_user.user_wins + 1)
        black_user.update_attributes(user_losses: black_user.user_losses + 1)
      end
    end
    redirect_to game_path(current_game)
    begin
      PrivatePub.publish_to("/games/#{current_game.id}", "window.location.reload();")
    rescue Errno::ECONNREFUSED
      flash.now[:alert] = "Pushing to Faye Failed"
    end
  end

  def request_draw
    current_game.update_attributes(draw_request: current_user.id)
    if current_game.player_missing?
      # if only player and click draw, then cancel/delete game and return to main page
      current_game.delete
      begin
        PrivatePub.publish_to( "/game_list_updates", "window.location.reload();")
      rescue Errno::ECONNREFUSED
        flash.now[:alert] = "Pushing to Faye Failed"
      end
      redirect_to root_path and return
    end
    redirect_to game_path(current_game)
    begin
      PrivatePub.publish_to("/games/#{current_game.id}", "window.location.reload();")
    rescue Errno::ECONNREFUSED
      flash.now[:alert] = "Pushing to Faye Failed"
    end
  end

  def accept_draw
    current_game.update_attributes(draw: true)
    white_user.update_attributes(user_draws: white_user.user_draws + 1)
    black_user.update_attributes(user_draws: black_user.user_draws + 1)
    redirect_to game_path(current_game)
    begin
      PrivatePub.publish_to("/games/#{current_game.id}", "window.location.reload();")
    rescue Errno::ECONNREFUSED
      flash.now[:alert] = "Pushing to Faye Failed"
    end
  end

  def reject_draw
    current_game.update_attributes(draw_request: nil)
    redirect_to game_path(current_game)
    begin
      PrivatePub.publish_to("/games/#{current_game.id}", "window.location.reload();")
    rescue Errno::ECONNREFUSED
      flash.now[:alert] = "Pushing to Faye Failed"
    end
  end

  private

  helper_method :current_game, :place_piece_td
  def current_game
    @current_game ||= Game.find(params[:id])
  end

  def board_display_piece_query(row, column)
    current_game.pieces.find do |f|
      f["x_position"] == column && f["y_position"] == row
    end
  end

  def place_piece_td(row, column)
    find_piece = board_display_piece_query(row, column)
    board_square = "<td data-x-position='#{column}'"
    if find_piece.nil?
      board_square += ">"
    else
      board_square += " data-piece-id='#{piece_id(find_piece)}' "
      board_square += "data-piece-type='#{piece_type(find_piece)}'>"
      image = ActionController::Base.helpers.image_tag find_piece
              .image_name, size: '40x45',
                           class: 'img-responsive center-block'
      board_square += ActionController::Base.helpers
                      .link_to image, piece_path(find_piece)
    end
    board_square + "</td>"
  end

  def piece_id(piece)
    piece.present? ? piece.id : nil
  end

  def piece_type(piece)
    piece.present? ? piece.piece_type : nil
  end

  def merge_player_color_choice_param
    if params[:game][:creator_plays_as_black] == '1'
      { black_user_id: current_user.id }
    else
      { white_user_id: current_user.id, user_turn: current_user.id }
    end
  end

  def game_create_params
    params.require(:game).permit(:game_name, :creator_plays_as_black,
                                 :white_user_id, :black_user_id, :user_turn)
      .merge(merge_player_color_choice_param)
  end

  def update_player
    if @game.white_user_id.nil?
      @game.update_attributes(white_user_id: current_user.id, user_turn: current_user.id)
      @game.set_pieces_white_user_id
    else
      @game.update_attributes(black_user_id: current_user.id)
      @game.set_pieces_black_user_id
    end
  end

  def handle_update_errors
    if @game.white_user_id? && @game.black_user_id?
      @game.errors.add(:base, "Game is full!")
    end
    flash[:alert] = @game.errors.full_messages.last
    redirect_to root_path
  end

  def black_user
    black_user ||= User.find(current_game.black_user.id)
  end

  def white_user
    white_user ||= User.find(current_game.white_user.id)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_blackside.html.erb
<!-- _blackside.html.erb 20160108 ~AMP -->
<div class="col-xs-12 col-sm-3 text-center blackside">
  <h4>Black Player</h4>
  <% if !current_game.black_user.nil? %>
    <%= link_to "#{current_game.black_user.email}", user_path(current_game.black_user.id) %>
  <% else %>
    <p>Waiting for player</p>
  <% end %>
  <% if user_signed_in? && current_user == current_game.black_user %>
    <% if current_game.draw == false && current_game.game_winner.nil? %>
      <% if current_game.draw_request.nil? %>
        <% if current_game.player_missing? %>
          <%= button_to 'Cancel game', request_draw_game_path(current_game), :class => 'btn btn-warning btn-sm controls', :confirm => 'Are you sure you want to cancel the game?', :method => :put %>
        <% else %>
          <%= button_to 'Offer draw', request_draw_game_path(current_game), :class => 'btn btn-warning btn-sm controls', :confirm => 'Are you sure you want to offer a draw?', :method => :put %>
        <% end %>
      <% elsif current_game.draw_request == current_game.white_user_id %>
        <%= button_to 'Accept draw', accept_draw_game_path(current_game), :class => 'btn btn-success btn-sm controls', :confirm => 'Are you sure you accept a draw?', :method => :put %>
        <%= button_to 'Reject draw', reject_draw_game_path(current_game), :class => 'btn btn-danger btn-sm controls', :confirm => 'Are you sure you want to reject the draw?', :method => :put %>
      <% else %>
        <%= button_to 'Draw pending...', '#', :class => 'btn btn-default btn-sm controls' %>
      <% end %>
      <% if !current_game.player_missing? %>
        <%= button_to 'Forfeit!', forfeit_game_path(current_game), :class => 'btn btn-danger btn-sm controls', :confirm => 'Are you sure you want to concede the game?', :method => :put %>
      <% end %>
    <% end %>
  <% end %>
  <p>Captured Pieces:</p>
  <% current_game.pieces.where(color: true, captured: true).order(:updated_at).each do |capped_piece| %>
    <%= image_tag capped_piece.image_name, size: "25x25" %>
  <% end %>
  <br /><br />
</div>

app/views/games/_whiteside.html.erb
<!-- _whiteside.html.erb 20160108 ~AMP -->
<div class="col-xs-12 col-sm-3 text-center whiteside">
  <h4>White Player</h4>
  <% if !current_game.white_user.nil? %>
    <%= link_to "#{current_game.white_user.email}", user_path(current_game.white_user.id) %>
  <% else %>
    <p>Waiting for player</p>
  <% end %>
  <% if user_signed_in? && current_user == current_game.white_user %>
    <% if current_game.draw == false && current_game.game_winner.nil? %>
      <% if current_game.draw_request.nil? %>
        <% if current_game.player_missing? %>
          <%= button_to 'Cancel game', request_draw_game_path(current_game), :class => 'btn btn-warning btn-sm controls', :confirm => 'Are you sure you want to cancel the game?', :method => :put %>
        <% else %>
          <%= button_to 'Offer draw', request_draw_game_path(current_game), :class => 'btn btn-warning btn-sm controls', :confirm => 'Are you sure you want to offer a draw?', :method => :put %>
        <% end %>
      <% elsif current_game.draw_request == current_game.black_user_id %>
        <%= button_to 'Accept draw', accept_draw_game_path(current_game), :class => 'btn btn-success btn-sm controls', :confirm => 'Are you sure you want to accept a draw?', :method => :put %>
        <%= button_to 'Reject draw', reject_draw_game_path(current_game), :class => 'btn btn-danger btn-sm controls', :confirm => 'Are you sure you want to reject the draw?', :method => :put %>
      <% else %>
        <%= button_to 'Draw pending...', '#', :class => 'btn btn-default btn-sm controls' %>
      <% end %>
      <% if !current_game.player_missing? %>
        <%= button_to 'Forfeit!', forfeit_game_path(current_game), :class => 'btn btn-danger btn-sm controls', :confirm => 'Are you sure you want to concede the game?', :method => :put %>
      <% end %>
    <% end %>
  <% end %>
  <p>Captured Pieces:</p>
  <% current_game.pieces.where(color: false, captured: true).order(:updated_at).each do |capped_piece| %>
    <%= image_tag capped_piece.image_name, size: "25x25" %>
  <% end %>
  <br /><br />
</div>

app/views/games/new.html.erb
<br />
<br />
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h3 class ="text-center">Create A New Game</h3>
    <%= simple_form_for @game, :url => games_path do |f| %>
      <%= f.input :game_name, label: 'Game Name', class: 'form-control' %>
      <%= f.input :creator_plays_as_black, as: :boolean, label: 'Play as Black', class: 'form-control' %>
      <br />
      <%= f.submit "Create", :class => 'btn btn-primary' %>
      <br />
    <% end %>
    <br />
  </div>
</div>

app/views/games/show.html.erb
<% if current_game && current_user && ((current_user.id == current_game.white_user_id) || (current_user.id == current_game.black_user_id)) %>
<script type="text/javascript">
$(document).ready(function () {
  $("[data-piece-id]").children("[href]").children('img').draggable({
    stack: "div",
    containment: ".chessboard",
    create: function(){$(this).data('position',$(this).position())},
    cursorAt:{left:15},
    cursor:'move',
    start: function( event, ui ) {
      $(this).stop(true,true);
    }
  });

  function snapToMiddle(dragger, target){
      var topMove = target.position().top - dragger.data('position').top + (target.outerHeight(true) - dragger.outerHeight(true)) / 2;
      var leftMove= target.position().left - dragger.data('position').left + (target.outerWidth(true) - dragger.outerWidth(true)) / 2;
      dragger.animate({top:topMove,left:leftMove},{duration:600,easing:'easeOutBack'});
  }
  
  $("td").droppable({
      drop: function(event, ui) {
        snapToMiddle(ui.draggable,$(this));
        var old_x_pos = ui.draggable.parent().parent().data('x-position');
        var old_y_pos = ui.draggable.parent().parent().parent().data('y-position');
        var x_pos = $(this).data('x-position');
        var y_pos = $(this).parent().data('y-position');
        var current_piece_id = ui.draggable.parent().parent().data('piece-id');
        var image_name = ui.draggable.attr("alt");
        var color = image_name.split(' ')[0];
        var piece_type = image_name.split(' ')[1];
        if (!((old_x_pos == x_pos)&&(old_y_pos == y_pos))) {  //prevent invalid move from popping up if you don't actually move
          if ((piece_type === "pawn") && ((color === "Black" && y_pos === 0) || (color === "White" && y_pos === 7))) {
            $.ajax({
                url: "<%=current_game.id%>/move",
                type: 'PUT',
                dataType: 'html',
                data: { piece_id: current_piece_id, x: x_pos, y: y_pos },
                  success: function () {
                    // goes to promotion url if pawn moving to last row
                    window.location.replace("/pieces/" + current_piece_id + "/promotion_choice");
                  },
                  error: function () {
                    location.reload(true); //refreshes page from server after failed move
                  }
            });
          }
          else {
            $.ajax({
                url: "<%=current_game.id%>/move",
                type: 'PUT',
                dataType: 'json',
                data: { piece_id: current_piece_id, x: x_pos, y: y_pos},
                  success: function () {
                    location.reload(true); //refreshes page from server after move
                  },
                  error: function () {
                    location.reload(true); //refreshes page from server after failed move
                  }
            });
          }
        }
      }
  });
});
</script>
<% end %>
<!-- games.show page -->
<% if current_game %>
  <br />
  <br />
  <div class="row">
    <div class="col-md-6 col-md-offset-3 text-center">
      <h3><%= current_game.game_name %></h3>
      <br />
        <% if !current_game.game_winner.nil? %>
          <% if current_game.game_winner == current_game.white_user_id %>
            <% if current_game.forfeit? %>
              <h4 class="turn-indicator">Black player forfeit. White player wins!</h4>
            <% else %>
              <h4 class="turn-indicator">Checkmate! White player wins!</h4>
            <% end %>
          <% else %>
            <% if current_game.forfeit? %>
              <h4 class="turn-indicator">White player forfeit. Black player wins!</h4>
            <% else %>
              <h4 class="turn-indicator">Checkmate! Black player wins!</h4>
              <% end %>
          <% end %>
        <% elsif current_game.draw? %>
          <% if current_game.user_turn == current_game.white_user_id %>
            <% if !current_game.draw_request.nil? %>
              <h4 class="turn-indicator">Game is a draw! Draw offer accepted. </h4>
            <% else %>
              <h4 class="turn-indicator">Game is a draw! White player in stalemate!</h4>
            <% end %>
          <% else %>
            <% if !current_game.draw_request.nil? %>
              <h4 class="turn-indicator">Game is a draw! Draw offer accepted. </h4>
            <% else %>
              <h4 class="turn-indicator">Game is a draw! Black player in stalemate!</h4>
            <% end %>
          <% end %>
        <% elsif current_game.player_missing? %>
          <% if current_game.white_user_id.nil? %>
            <h4 class="turn-indicator">Waiting for white player to join...</h4>
          <% else %>
            <h4 class="turn-indicator">Waiting for black player to join...</h4>
          <% end %>
        <% elsif current_user && current_game.user_turn == current_user.id %>
          <% if current_game.user_turn == current_game.white_user_id %>
            <h4 class="turn-indicator">It is your turn! (white)</h4>
          <% else %>
            <h4 class="turn-indicator">It is your turn! (black)</h4>
          <% end %>
        <% else  %>
          <% if current_user %>
            <% if current_game.user_turn == current_game.white_user_id %>
              <h4 class="turn-indicator">It is your opponent's turn (white)</h4>
            <% else %>
              <h4 class="turn-indicator">It is your opponent's turn (black)</h4>
            <% end %>
          <% else %>
            <% if current_game.user_turn == current_game.white_user_id %>
              <h4 class="turn-indicator">White player's turn</h4>
            <% else %>
              <h4 class="turn-indicator">Black player's turn</h4>
            <% end %>
          <% end %>
        <% end %>
      <br />
      <% if current_game.check? && current_game.game_winner.nil?%>
        <% if current_game.user_turn == current_game.white_user_id %>
          <h4 class ="check-message">White player is in check!</h4>
        <% else %>
          <h4 class ="check-message">Black player is in check!</h4>
        <% end %>
      <% end %>
    </div>
  </div>
  <!-- Arrangement of partials and chessboards is optimized for mobile. -->
  <% if current_user && current_user.id == current_game.black_user_id %>
    <%= render partial: 'whiteside' %>
    <div class="col-xs-12 col-sm-6">
      <table class="chessboard">
        <% (0..7).each do |row| %>
            <tr data-y-position="<%= row %>" >
              <% (0..7).to_a.reverse.each do |column| %>
                <%= place_piece_td(row, column).html_safe %>
              <% end %>
            </tr>
        <% end %>
      </table>
    </div>
    <%= render partial: 'blackside' %>
  <% else %>
    <%= render partial: 'blackside' %>
    <div class="col-xs-12 col-sm-6">
      <table class="chessboard">
        <% (0..7).to_a.reverse.each do |row| %>
          <tr data-y-position="<%= row %>" >
            <% (0..7).each do |column| %>
              <%= place_piece_td(row, column).html_safe %>
            <% end %>
          </tr>
        <% end %>
      </table>
    </div>
    <%= render partial: 'whiteside' %>
  <% end %>
<% end %>
<%= subscribe_to "/games/" + @game.id.to_s %>